const jsonServer = require("json-server");
const server = jsonServer.create();
const cors = require('cors');
const router = jsonServer.router("db.json");
server.use(cors);
const middlewares = jsonServer.defaults({ static: "./build" });
const port = process.env.PORT || 8000;
server.use(middlewares);
server.use(router);
server.listen(port);
